### ISSUE TITLE
Desenvolvimento do Product Backlog

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar-Usuario#58]
### Descrição:
Issue destinada a criação e desenvolvimento do documento Product Backlog.

### Tarefas:
- [x] Reavaliar o Backlog levantado na issue #46;
- [x] Inserir histórias ainda restantes, seguindo os requisitos levantados #38 ; 
- [x] Criar documento na pasta docs ou na nova branch criada para a gh pages #55;
- [x] Definir pontuação para as histórias de usuário.

### Critérios de aceitação:
- [x] Considerar o Backlog condizente com as necessidades do produto;
- [x] Considerar o Product Backlog condizente com os requisitos levantados.
- [x] Conversar com o grupo sobre as histórias levantadas.
- [x] Pontuação das histórias devidamente levantadas;
- [x] Documento estar devidamente inserido na pasta docs ou na gh pages.
